excerpt_separator: ""
pygments: false
rouge: true
markdown: kramdown
title: dsgn coder
tagline: Tales of a Web Developer
description: Web Development and Design
paginate: 3
author:
  dsgncoder:
    name: dsgncoder
    url: http://dsgncoder.github.io
    description: Web development from the view of a front-end Web Developer, focused on all things HTML, CSS and Javascript.
